import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import SessionWrapper from "@/components/SessionWrapper";

import "@fontsource/roboto/400.css";
// import '@/styles/globals.css'
import "@/styles/custom.css";
import "@/styles/post-tags.css";

import "@/styles/prism.js/prism-tomorrow-night.css";
import "@/styles/prism.js/prism-line-numbers.min.css";
import "highlight.js/styles/default.css";
import "@/../public/assets/libs/prism.js/prism-tomorrow-night.js";
import "@/../public/assets/libs/prism.js/prism-line-numbers.min.js";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

export const metadata: Metadata = {
    title: "Vedev Blog",
    description: "Generated by vedev.guru",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <SessionWrapper>
            <html lang="en">
                <body>
                    <AntdRegistry>{children}</AntdRegistry>
                </body>
            </html>
        </SessionWrapper>
    );
}
