import Head from 'next/head'
import styles from '../styles/Home.module.css'
import PrismHigLighter from '../components/syntax-highlighter'

export default function Home() {
  const javascript = `
function add(a, b, c) {
  return a + b + c;
}
`

const htmlCode = `
    <div>
      <h1> PrismJS Tutorial </h1>
      <p>
      Prism is a lightweight, extensible syntax highlighter, built with modern web standards in mind.
      </p>
    </div>
`;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PrismHigLighter code={javascript} language="javascript" />
      <PrismHigLighter code={htmlCode} language="html" />
      
    </>
  )
}
