import Head from 'next/head'
import styles from '../styles/Home.module.css'
import PrismHigLighterRaw from '../components/syntax-highlighter-raw'
import PrismHigLighterLine from '../components/syntax-highlighter-with-lines'
import PrismHigLighterRenderer from '../components/syntax-highlighter-prism-react-renderer'
import PrismHigLighter from '../components/syntax-highlighter'

export default function Home() {
  var markdownContent = `
\`\`\`js
function add(a, b, c) {
  return a + b + c;
}
\`\`\`
`
// markdownContent = `## Hello`

const javascriptCodeBlock = `
function add(a, b, c) {
  return a + b + c;
}
`
const htmlCodeBlock = `
    <div>
      <h1> PrismJS Tutorial </h1>
      <p>
      Prism is a lightweight, extensible syntax highlighter, built with modern web standards in mind.
      </p>
    </div>
`;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PrismHigLighter markdownContent={markdownContent} />
      {/* <PrismHigLighterLine markdownContent={markdownContent} />
      <PrismHigLighterRenderer codeblock={javascriptCodeBlock} language="javascript" />
      <PrismHigLighterRenderer codeblock={htmlCodeBlock} language="html" />
      <PrismHigLighterRaw code={javascriptCodeBlock} language="javascript" />
      <PrismHigLighterRaw code={htmlCodeBlock} language="html" /> */}
    </>
  )
}
